GET http://localhost:5001/todos

###

POST http://localhost:5001/todo/create
Content-Type: application/json

{
  "text": "Test Post"
}

###
DELETE http://localhost:5001/todos/delete-all 


###
DELETE http://localhost:5001/todo/delete/6555c6cf447b889efb5de45c

###
PUT http://localhost:5001/todo/editComplete/6558a1b2ea0532ed59bb970b
